using System;
using System.Collections.Generic;
using System.Linq;
using Hai.ComboGesture.Scripts.Components;
using Hai.ComboGesture.Scripts.Editor.Internal.CgeAac;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace Hai.ComboGesture.Scripts.Editor.Internal
{
    internal class CgeLayerForExpressionsView
    {
        private readonly CgeFeatureToggles _featuresToggles;
        private readonly AvatarMask _expressionsAvatarMask;
        private readonly AnimationClip _emptyClip;
        private readonly string _activityStageName;
        private readonly CgeConflictPrevention _conflictPrevention;
        private readonly CgeAssetContainer _assetContainer;
        private readonly ConflictCvrLayerMode _compilerConflictFxLayerMode;
        private readonly AnimationClip _compilerIgnoreParamList;
        private readonly AnimationClip _compilerFallbackParamList;
        private readonly AnimatorController _animatorController;
        private readonly List<CgeManifestBinding> _manifestBindings;
        private readonly Animator _avatarDescriptorNullable;
        private readonly string _mmdCompatibilityToggleParameter;

        public CgeLayerForExpressionsView(CgeFeatureToggles featuresToggles,
            AvatarMask expressionsAvatarMask,
            AnimationClip emptyClip,
            string activityStageName,
            CgeConflictPrevention conflictPrevention,
            CgeAssetContainer assetContainer,
            ConflictCvrLayerMode compilerConflictFxLayerMode,
            AnimationClip compilerIgnoreParamList,
            AnimationClip compilerFallbackParamList,
            AnimatorController animatorController,
            List<CgeManifestBinding> manifestBindings,
            Animator avatarDescriptorNullable,
            string mmdCompatibilityToggleParameter)
        {
            _featuresToggles = featuresToggles;
            _expressionsAvatarMask = expressionsAvatarMask;
            _emptyClip = emptyClip;
            _activityStageName = activityStageName;
            _conflictPrevention = conflictPrevention;
            _assetContainer = assetContainer;
            _compilerConflictFxLayerMode = compilerConflictFxLayerMode;
            _compilerIgnoreParamList = compilerIgnoreParamList;
            _compilerFallbackParamList = compilerFallbackParamList;
            _animatorController = animatorController;
            _manifestBindings = manifestBindings;
            _avatarDescriptorNullable = avatarDescriptorNullable;
            _mmdCompatibilityToggleParameter = mmdCompatibilityToggleParameter;
        }

        public void Create()
        {
            EditorUtility.DisplayProgressBar("ComboGestureExpressions", "Generating avatar mask", 0f);

            var activityManifests = _manifestBindings;
            var animationNeutralizer = new AnimationNeutralizer(
                activityManifests,
                _compilerConflictFxLayerMode,
                _compilerIgnoreParamList,
                _compilerFallbackParamList,
                _assetContainer,
                _conflictPrevention.ShouldGenerateExhaustiveAnimations,
                _emptyClip,
                Feature(CgeFeatureToggles.DoNotFixSingleKeyframes),
                _avatarDescriptorNullable
            );

            var avatarMaskNullable = animationNeutralizer.GenerateAvatarMaskInsideContainerIfApplicableOrNull();

            EditorUtility.DisplayProgressBar("ComboGestureExpressions", "Reinitializing layer", 0f);

            var layer = ReinitializeLayer(avatarMaskNullable);

            var defaultState = layer.NewState("Default")
                .WithWriteDefaultsSetTo(_conflictPrevention.ShouldWriteDefaults);

            EditorUtility.DisplayProgressBar("ComboGestureExpressions", "Generating animations", 0f);

            activityManifests = animationNeutralizer.NeutralizeManifestAnimationsInsideContainer();

            EditorUtility.DisplayProgressBar("ComboGestureExpressions", "Saving", 0f);

            CgeAssetContainer.GlobalSave();

            EditorUtility.DisplayProgressBar("ComboGestureExpressions", "Creating blend trees", 0f);

            // The blend tree auto weight corrector assumes that all of the Manifests' blend trees have been autogenerated.
            // This remains true as long as the Animation Neutralizer's "NeutralizeManifestAnimationsInsideContainer" function is executed before this.
            activityManifests = new CgeBlendTreeAutoWeightCorrector(activityManifests, _assetContainer)
                .MutateAndCorrectExistingBlendTrees();

            foreach (var parameter in AllParametersUsedByManifests(activityManifests))
            {
                layer.FloatParameter(parameter);
            }

            EditorUtility.DisplayProgressBar("ComboGestureExpressions", "Decomposing", 0f);

            var combinator = new CgeIntermediateCombinator(activityManifests);

            new CgeExpressionCombiner(_assetContainer,
                layer,
                combinator.ComposedBehaviours,
                _activityStageName,
                _conflictPrevention.ShouldWriteDefaults,
                defaultState,
                _mmdCompatibilityToggleParameter,
                _animatorController.layers.ToList().FindIndex(ctrl => ctrl.name == "CGCVR_GestureExp")
            ).Populate();
        }

        private static List<string> AllParametersUsedByManifests(List<CgeManifestBinding> activityManifests)
        {
            return AllParametersUsedByBlendTrees(activityManifests)
                .Concat(AllParametersUsedByMassiveBlends(activityManifests))
                .ToList();
        }

        private static List<string> AllParametersUsedByBlendTrees(List<CgeManifestBinding> activityManifests)
        {
            return activityManifests
                .SelectMany(binding => binding.Manifest.AllBlendTreesFoundRecursively())
                .SelectMany(FindParametersOfBlendTree)
                .Distinct()
                .ToList();
        }

        private static List<string> AllParametersUsedByMassiveBlends(List<CgeManifestBinding> activityManifests)
        {
            return activityManifests
                .Where(binding => binding.Manifest.Kind() == CgeManifestKind.Massive)
                .SelectMany(binding =>
                {
                    var manifest = (CgeMassiveBlendManifest)binding.Manifest;
                    switch (manifest.Mode)
                    {
                        case CgeMassiveBlendMode.Simple:
                        case CgeMassiveBlendMode.TwoDirections:
                            return new List<string> { manifest.SimpleParameterName };
                        case CgeMassiveBlendMode.ComplexBlendTree:
                            return FindParametersOfBlendTree(manifest.BlendTree);
                        default:
                            throw new ArgumentOutOfRangeException();
                    }
                })
                .Distinct()
                .ToList();
        }

        private static IEnumerable<string> FindParametersOfBlendTree(BlendTree tree)
        {
            switch (tree.blendType)
            {
                case BlendTreeType.Simple1D:
                    return new List<string> {tree.blendParameter};
                case BlendTreeType.SimpleDirectional2D:
                    return new List<string> {tree.blendParameter, tree.blendParameterY};
                case BlendTreeType.FreeformDirectional2D:
                    return new List<string> {tree.blendParameter, tree.blendParameterY};
                case BlendTreeType.FreeformCartesian2D:
                    return new List<string> {tree.blendParameter, tree.blendParameterY};
                case BlendTreeType.Direct:
                    return tree.children.Select(motion => motion.directBlendParameter).ToList();
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        private CgeAacFlLayer ReinitializeLayer(AvatarMask avatarMaskNullable)
        {
            return _assetContainer.ExposeCgeAac().CreateSupportingArbitraryControllerLayer(_animatorController, "CGCVR_GestureExp")
                .WithAvatarMask(avatarMaskNullable != null ? avatarMaskNullable : _expressionsAvatarMask);
        }

        private bool Feature(CgeFeatureToggles feature)
        {
            return (_featuresToggles & feature) == feature;
        }
    }
}
